### PR TITLE
Upgrade to Slick 3.5

### PR DESCRIPTION
**Pull request by Tvaroh**
Please consider this, as it's blocking upgrading to Slick 3.5 for us. Thank you!

### CODE REVIEW

**Comment by kubukoz** [comment]
Man, it's been a while since I looked at this project...

So first of all, is 3.5 not binary compatible with earlier versions?

**Comment by kubukoz** [comment]
ah, I see, it's at least not source-compatible (`DatabaseDef` disappeared?)

**Comment by kubukoz** [comment]
figured this might be a good time to add Scala 3 support, just in case somebody's stuck with Slick and wants to switch... this could be you too, actually 😅

I'll tag as 0.6.0 once we merge.

**Comment by kubukoz** [comment]
FYI this is released in 0.6.0, CI doesn't want to cooperate (probably something to do with the PGP/GPG secrets, I don't want to investigate that right now) but I ran `tlRelease` locally after migrating the build to sbt-typelevel. Should be up within the hour.

**Comment by Tvaroh** [comment]
Thanks for the quick turnaround @kubukoz 🙏

**Pull request merged**
